runtime: nodejs10
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301
instance_class: F4
automatic_scaling:
  min_instances: 5
  max_instances: 100
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50